#!/bin/bash
#
# A simple script to push both CImg and G'MIC updates on the git repo.
#
COM="."
if [ -n "$*" ]; then COM="$*"; fi

echo -e "\n  ** CImg\n"
cd $HOME/work/src/CImg
git commit -uno -am "$COM"
git push

echo -e "\n  ** gmic\n"
cd $HOME/work/src/gmic
git commit -uno -am "$COM"
git push

cd $HOME/work/src/gmic
cp -rf COPYING README README.md $HOME/work/src/gmic-community
cp -rf COPYING README README.md $HOME/work/src/gmic-minimal
cp -rf src/*.cpp src/*.h src/*.c src/Makefile src/*.scm $HOME/work/src/gmic-minimal/src

echo -e "\n  ** gmic-community\n"
cd $HOME/work/src/gmic-community
git pull
git commit -uno -am "$COM"
git push

echo -e "\n  ** gmic-minimal\n"
cd $HOME/work/src/gmic-minimal
git commit -uno -am "$COM"
git push
